\set ON_ERROR_STOP on

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM uok_app;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM uok_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM uok_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM uok_app;

GRANT SELECT ON TABLE schema_migrations TO uok_app;
GRANT SELECT, INSERT, UPDATE ON TABLE kernel_command_receipts TO uok_app;
GRANT SELECT, INSERT ON TABLE kernel_audit_events TO uok_app;
GRANT SELECT, INSERT ON TABLE kernel_outbox_events TO uok_app;
GRANT SELECT, INSERT, UPDATE ON TABLE master_parties TO uok_app;
