\set ON_ERROR_STOP on

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM uok_outbox;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM uok_outbox;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM uok_outbox;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM uok_outbox;

GRANT SELECT, UPDATE ON TABLE kernel_outbox_events TO uok_outbox;
GRANT SELECT, INSERT, UPDATE ON TABLE kernel_durable_jobs TO uok_outbox;
GRANT SELECT, INSERT ON TABLE kernel_outbox_deliveries TO uok_outbox;
