defmodule UokNextWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :uok_next

  @dev_routes Application.compile_env(:uok_next, :dev_routes, false)

  if @dev_routes do
    @session_options [
      store: :cookie,
      key: "_uok_next_key",
      signing_salt: "M7mu8DtT",
      encryption_salt: "4ytqjxVp",
      same_site: "Strict",
      http_only: true
    ]

    socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: @session_options]],
      longpoll: [connect_info: [session: @session_options]]
  end

  plug UokNextWeb.ShellSecurityHeaders

  plug Plug.Static,
    at: "/uok-ui",
    from: {:uok_next, "priv/static/uok-ui"},
    gzip: not code_reloading?,
    only: ~w(index.html),
    cache_control_for_etags: "no-store"

  plug Plug.Static,
    at: "/uok-ui",
    from: {:uok_next, "priv/static/uok-ui"},
    gzip: not code_reloading?,
    only: ~w(assets),
    cache_control_for_etags: "public, max-age=31536000, immutable"

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :uok_next,
    gzip: not code_reloading?,
    only: UokNextWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :uok_next
  end

  if @dev_routes do
    plug Phoenix.LiveDashboard.RequestLogger,
      param_key: "request_logger",
      cookie_key: "request_logger"
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Head

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["application/json", "multipart/form-data", "application/x-www-form-urlencoded"],
    json_decoder: Phoenix.json_library(),
    length: 8_650_000,
    read_length: 1_000_000,
    read_timeout: 5_000

  if @dev_routes do
    plug Plug.Session, @session_options
  end

  plug UokNextWeb.Router
end
