defmodule UokNextWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :uok_next

  @dev_routes Application.compile_env(:uok_next, :dev_routes, false)
  @framework_spike_routes Application.compile_env(:uok_next, :framework_spike_routes, false)

  if @dev_routes do
    @session_options [
      store: :cookie,
      key: "_uok_next_key",
      signing_salt: "M7mu8DtT",
      encryption_salt: "4ytqjxVp",
      same_site: "Strict",
      http_only: true
    ]

    socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: @session_options]],
      longpoll: [connect_info: [session: @session_options]]
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :uok_next,
    gzip: not code_reloading?,
    only: UokNextWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :uok_next
  end

  if @dev_routes do
    plug Phoenix.LiveDashboard.RequestLogger,
      param_key: "request_logger",
      cookie_key: "request_logger"
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Head

  if @framework_spike_routes do
    plug Plug.Parsers,
      parsers: [:json],
      pass: ["application/json"],
      json_decoder: Phoenix.json_library(),
      length: 64_000,
      read_length: 64_000,
      read_timeout: 2_000
  end

  if @dev_routes do
    plug Plug.Session, @session_options
  end

  plug UokNextWeb.Router
end
